- index.js
- package.json
> fix(get): use request instead of axios, because of follow redirection

- package.json
- src/convert.js
- src/parse-float-with-comma.js
- test/convert-test.js
- test/parse-float-with-comma-test.js
fixes #14
```
Before
{
"name": "Gmail Offline",
"url": "https://chrome.google.com/webstore/detail/gmail-offline/ejidjjhkpiempkbhmpbfngldlkglhimk",
"image": "https://lh4.googleusercontent.com/RpEbYErNLKvSWgk6I08RCwYdaO8ss2XObyvI9tibrvKmMAIIvV2rxFStRIZYwj0vI91TTv3MMA=s128-h128-e365",
"version": "1.20",
"price": "$0",
"priceCurrency": "USD",
"interactionCount": {
"UserDownloads": "4,410,977"
},
"operatingSystems": "Chrome",
"ratingValue": "4.137782288759198",
"ratingCount": "11823",
"id": "ejidjjhkpiempkbhmpbfngldlkglhimk"
}
After
{
"name": "Gmail Offline",
"url": "https://chrome.google.com/webstore/detail/gmail-offline/ejidjjhkpiempkbhmpbfngldlkglhimk",
"image": "https://lh4.googleusercontent.com/RpEbYErNLKvSWgk6I08RCwYdaO8ss2XObyvI9tibrvKmMAIIvV2rxFStRIZYwj0vI91TTv3MMA=s128-h128-e365", …
```
> feat(convert): ratingCount, ratingValue, UserDownloads to number

- package.json
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6040939966041701004">David Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6040939966041701004">2015-06-28 Updated permissions - Tachikoma.io</a>
> Exec tachikoma update 20150822193919

- package.json
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6056159002567849630">David Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6056159002567849630">2015-06-28 Updated permissions - Tachikoma.io</a>
> Exec tachikoma update 20151003193522

- package.json
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6066305862043205974">David Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6066305862043205974">2015-06-28 Updated permissions - Tachikoma.io</a>
> Exec tachikoma update 20151031193359

- package.json
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6071379293960244276">David Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6071379293960244276">2015-06-28 Updated permissions - Tachikoma.io</a>
> Exec tachikoma update 20151114193402

- package.json
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6073916007373893575">David Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6073916007373893575">2015-06-28 Updated permissions - Tachikoma.io</a>
> Exec tachikoma update 20151121193407

- package.json
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6081526148100193299">David Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6081526148100193299">2015-06-28 Updated permissions - Tachikoma.io</a>
> Exec tachikoma update 20151212193405

- package.json
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6091673008809682009">David Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6091673008809682009">2015-06-28 Updated permissions - Tachikoma.io</a>
> Exec tachikoma update 20160109193440

- package.json
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6099283159786803021">David Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6099283159786803021">2015-06-28 Updated permissions - Tachikoma.io</a>
> Exec tachikoma update 20160130193454

- package.json
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6122113593304724439">David Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6122113593304724439">2015-06-28 Updated permissions - Tachikoma.io</a>
> Exec tachikoma update 20160402193630

- package.json
Use `conventional-changelog-cli`
> conventional changelog update

- package.json
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6127187019030315375">David Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6127187019030315375">2015-06-28 Updated permissions - Tachikoma.io</a>
> Exec tachikoma update 20160416193821

- readme.md
> Price is not returned for paid apps,
> Price is missing currency symbol for free apps,
Detail page does not have price and priceCurrency for paid apps.
There is no currency symbol for free apps.
Only I can do is updating readme ;(
fixes #64
> Update readme for free and paid apps

- package.json
> chore(deps): npm update

- src/convert.js
- test/convert-test.js
Reverts pandawing/node-chrome-web-store-item-property#195
> Revert "Update convert.js"

- .travis.yml
- package.json
> chore(ci): test against nodejs v10, v12

- .gitignore
> chore(app): ignore lockfile

- package.json
> chore(deps): update dev dependencies

- package.json
> chore(deps): drop devid

- package.json
This reverts commit 74c149a46fd08e9de15d6fdc4479d98745688de9.
> feat(app): requires node v8

- package.json
- src/convert.js
Use htmlparser2 directly.
fixes #224
> Use htmlparser2 instead of cheerio

- .travis.yml
> test on node 14, 15
